# Generated by Django 5.0.7 on 2024-09-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='fst_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='lst_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
