# Generated by Django 5.0.7 on 2024-09-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_musician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albm_name',
            new_name='album_name',
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
